// Code generated by cudago. Edit at your own risk.
package cudago

import (
    "github.com/InternatBlackhole/cudago/cuda"
	"unsafe"
)


//here just to force usage of unsafe package
var __razdalja_5_useless_var__ unsafe.Pointer = nil

const (
	KeyRazdalja_5 = "razdalja_5"
)


type vectordistance5Args struct {
    p uintptr
    a uintptr
    b uintptr
    len int32

}

/*var (
    vectordistance5Args = vectordistance5Args{}

)*/







func VectorDistance5(grid, block cuda.Dim3, p uintptr, a uintptr, b uintptr, len int32) error {
	err := autoloadLib_razdalja_5()
	if err != nil {
		return err
	}
	kern, err := getKernel("razdalja_5", "vectorDistance5")
	if err != nil {
		return err
	}
	
	params := vectordistance5Args{
	    p: p,
	    a: a,
	    b: b,
	    len: len,
	
	}
	
	return kern.Launch(grid, block, unsafe.Pointer(&params.p), unsafe.Pointer(&params.a), unsafe.Pointer(&params.b), unsafe.Pointer(&params.len))
}

func VectorDistance5Ex(grid, block cuda.Dim3, sharedMem uint64, stream *cuda.Stream, p uintptr, a uintptr, b uintptr, len int32) error {
	err := autoloadLib_razdalja_5()
	if err != nil {
		return err
	}
	kern, err := getKernel("razdalja_5", "vectorDistance5")
	if err != nil {
		return err
	}
	
	params := vectordistance5Args{
	    p: p,
	    a: a,
	    b: b,
	    len: len,
	
	}
	
	return kern.LaunchEx(grid, block, sharedMem, stream, unsafe.Pointer(&params.p), unsafe.Pointer(&params.a), unsafe.Pointer(&params.b), unsafe.Pointer(&params.len))
}



var loaded_razdalja_5 = false


func autoloadLib_razdalja_5() error {
	if loaded_razdalja_5 {
		return nil
	}
	err := InitLibrary([]byte(Razdalja_5_ptxCode), "razdalja_5")
	if err != nil {
		return err
	}
	loaded_razdalja_5 = true
	return nil
}

const Razdalja_5_ptxCode = `//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-34431801
// Cuda compilation tools, release 12.6, V12.6.20
// Based on NVVM 7.0.1
//

.version 8.5
.target sm_52
.address_size 64

	// .globl	vectorDistance5
.extern .shared .align 16 .b8 part[];

.visible .entry vectorDistance5(
	.param .u64 vectorDistance5_param_0,
	.param .u64 vectorDistance5_param_1,
	.param .u64 vectorDistance5_param_2,
	.param .u32 vectorDistance5_param_3
)
{
	.reg .pred 	%p<7>;
	.reg .f32 	%f<12>;
	.reg .b32 	%r<18>;
	.reg .b64 	%rd<18>;


	ld.param.u64 	%rd4, [vectorDistance5_param_0];
	ld.param.u64 	%rd5, [vectorDistance5_param_1];
	ld.param.u64 	%rd6, [vectorDistance5_param_2];
	ld.param.u32 	%r10, [vectorDistance5_param_3];
	mov.u32 	%r1, %tid.x;
	mul.wide.u32 	%rd7, %r1, 4;
	mov.u64 	%rd8, part;
	add.s64 	%rd1, %rd8, %rd7;
	mov.u32 	%r11, 0;
	st.shared.u32 	[%rd1], %r11;
	mov.u32 	%r2, %ntid.x;
	mov.u32 	%r3, %ctaid.x;
	mad.lo.s32 	%r16, %r3, %r2, %r1;
	setp.ge.s32 	%p1, %r16, %r10;
	@%p1 bra 	$L__BB0_4;

	mov.u32 	%r12, %nctaid.x;
	mul.lo.s32 	%r5, %r12, %r2;
	cvta.to.global.u64 	%rd2, %rd5;
	cvta.to.global.u64 	%rd3, %rd6;
	mov.f32 	%f11, 0f00000000;

$L__BB0_2:
	mul.wide.s32 	%rd9, %r16, 4;
	add.s64 	%rd10, %rd2, %rd9;
	add.s64 	%rd11, %rd3, %rd9;
	ld.global.nc.f32 	%f4, [%rd11];
	ld.global.nc.f32 	%f5, [%rd10];
	sub.f32 	%f6, %f5, %f4;
	fma.rn.f32 	%f11, %f6, %f6, %f11;
	add.s32 	%r16, %r16, %r5;
	setp.lt.s32 	%p2, %r16, %r10;
	@%p2 bra 	$L__BB0_2;

	st.shared.f32 	[%rd1], %f11;

$L__BB0_4:
	bar.sync 	0;
	setp.lt.u32 	%p3, %r2, 2;
	@%p3 bra 	$L__BB0_9;

	mov.u32 	%r17, 1;

$L__BB0_6:
	shl.b32 	%r9, %r17, 1;
	rem.u32 	%r14, %r1, %r9;
	setp.ne.s32 	%p4, %r14, 0;
	@%p4 bra 	$L__BB0_8;

	add.s32 	%r15, %r17, %r1;
	mul.wide.u32 	%rd12, %r15, 4;
	add.s64 	%rd14, %rd8, %rd12;
	ld.shared.f32 	%f7, [%rd1];
	ld.shared.f32 	%f8, [%rd14];
	add.f32 	%f9, %f8, %f7;
	st.shared.f32 	[%rd1], %f9;

$L__BB0_8:
	bar.sync 	0;
	setp.lt.u32 	%p5, %r9, %r2;
	mov.u32 	%r17, %r9;
	@%p5 bra 	$L__BB0_6;

$L__BB0_9:
	setp.ne.s32 	%p6, %r1, 0;
	@%p6 bra 	$L__BB0_11;

	ld.shared.f32 	%f10, [part];
	cvta.to.global.u64 	%rd15, %rd4;
	mul.wide.u32 	%rd16, %r3, 4;
	add.s64 	%rd17, %rd15, %rd16;
	st.global.f32 	[%rd17], %f10;

$L__BB0_11:
	ret;

}

`
