// Code generated by cudago. Edit at your own risk.
package cudago

import (
    "github.com/InternatBlackhole/cudago/cuda"
	"unsafe"
)


//here just to force usage of unsafe package
var __razdalja_ld3_useless_var__ unsafe.Pointer = nil

const (
	KeyRazdalja_ld3 = "razdalja_ld3"
)


type vectordistanceld3Args struct {
    p uintptr
    a uintptr
    b uintptr
    len int32

}

/*var (
    vectordistanceld3Args = vectordistanceld3Args{}

)*/







func VectorDistanceLD3(grid, block cuda.Dim3, p uintptr, a uintptr, b uintptr, len int32) error {
	err := autoloadLib_razdalja_ld3()
	if err != nil {
		return err
	}
	kern, err := getKernel("razdalja_ld3", "vectorDistanceLD3")
	if err != nil {
		return err
	}
	
	params := vectordistanceld3Args{
	    p: p,
	    a: a,
	    b: b,
	    len: len,
	
	}
	
	return kern.Launch(grid, block, unsafe.Pointer(&params.p), unsafe.Pointer(&params.a), unsafe.Pointer(&params.b), unsafe.Pointer(&params.len))
}

func VectorDistanceLD3Ex(grid, block cuda.Dim3, sharedMem uint64, stream *cuda.Stream, p uintptr, a uintptr, b uintptr, len int32) error {
	err := autoloadLib_razdalja_ld3()
	if err != nil {
		return err
	}
	kern, err := getKernel("razdalja_ld3", "vectorDistanceLD3")
	if err != nil {
		return err
	}
	
	params := vectordistanceld3Args{
	    p: p,
	    a: a,
	    b: b,
	    len: len,
	
	}
	
	return kern.LaunchEx(grid, block, sharedMem, stream, unsafe.Pointer(&params.p), unsafe.Pointer(&params.a), unsafe.Pointer(&params.b), unsafe.Pointer(&params.len))
}



var loaded_razdalja_ld3 = false


func autoloadLib_razdalja_ld3() error {
	if loaded_razdalja_ld3 {
		return nil
	}
	err := InitLibrary([]byte(Razdalja_ld3_ptxCode), "razdalja_ld3")
	if err != nil {
		return err
	}
	loaded_razdalja_ld3 = true
	return nil
}

const Razdalja_ld3_ptxCode = `//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-34431801
// Cuda compilation tools, release 12.6, V12.6.20
// Based on NVVM 7.0.1
//

.version 8.5
.target sm_52
.address_size 64

	// .globl	vectorDistanceLD3
.extern .shared .align 16 .b8 part[];

.visible .entry vectorDistanceLD3(
	.param .u64 vectorDistanceLD3_param_0,
	.param .u64 vectorDistanceLD3_param_1,
	.param .u64 vectorDistanceLD3_param_2,
	.param .u32 vectorDistanceLD3_param_3
)
{
	.reg .pred 	%p<7>;
	.reg .f32 	%f<12>;
	.reg .b32 	%r<17>;
	.reg .b64 	%rd<18>;


	ld.param.u64 	%rd4, [vectorDistanceLD3_param_0];
	ld.param.u64 	%rd5, [vectorDistanceLD3_param_1];
	ld.param.u64 	%rd6, [vectorDistanceLD3_param_2];
	ld.param.u32 	%r11, [vectorDistanceLD3_param_3];
	mov.u32 	%r1, %tid.x;
	mul.wide.u32 	%rd7, %r1, 4;
	mov.u64 	%rd8, part;
	add.s64 	%rd1, %rd8, %rd7;
	mov.u32 	%r12, 0;
	st.shared.u32 	[%rd1], %r12;
	mov.u32 	%r2, %ntid.x;
	mov.u32 	%r3, %ctaid.x;
	mad.lo.s32 	%r15, %r3, %r2, %r1;
	setp.ge.s32 	%p1, %r15, %r11;
	@%p1 bra 	$L__BB0_4;

	mov.u32 	%r13, %nctaid.x;
	mul.lo.s32 	%r5, %r13, %r2;
	cvta.to.global.u64 	%rd2, %rd5;
	cvta.to.global.u64 	%rd3, %rd6;
	mov.f32 	%f11, 0f00000000;

$L__BB0_2:
	mul.wide.s32 	%rd9, %r15, 4;
	add.s64 	%rd10, %rd2, %rd9;
	add.s64 	%rd11, %rd3, %rd9;
	ld.global.nc.f32 	%f4, [%rd11];
	ld.global.nc.f32 	%f5, [%rd10];
	sub.f32 	%f6, %f5, %f4;
	fma.rn.f32 	%f11, %f6, %f6, %f11;
	add.s32 	%r15, %r15, %r5;
	setp.lt.s32 	%p2, %r15, %r11;
	@%p2 bra 	$L__BB0_2;

	st.shared.f32 	[%rd1], %f11;

$L__BB0_4:
	bar.sync 	0;
	shr.u32 	%r16, %r2, 1;
	setp.eq.s32 	%p3, %r16, 0;
	@%p3 bra 	$L__BB0_8;

$L__BB0_5:
	setp.ge.u32 	%p4, %r1, %r16;
	@%p4 bra 	$L__BB0_7;

	add.s32 	%r14, %r16, %r1;
	mul.wide.u32 	%rd12, %r14, 4;
	add.s64 	%rd14, %rd8, %rd12;
	ld.shared.f32 	%f7, [%rd1];
	ld.shared.f32 	%f8, [%rd14];
	add.f32 	%f9, %f8, %f7;
	st.shared.f32 	[%rd1], %f9;

$L__BB0_7:
	bar.sync 	0;
	shr.u32 	%r16, %r16, 1;
	setp.ne.s32 	%p5, %r16, 0;
	@%p5 bra 	$L__BB0_5;

$L__BB0_8:
	setp.ne.s32 	%p6, %r1, 0;
	@%p6 bra 	$L__BB0_10;

	ld.shared.f32 	%f10, [part];
	cvta.to.global.u64 	%rd15, %rd4;
	mul.wide.u32 	%rd16, %r3, 4;
	add.s64 	%rd17, %rd15, %rd16;
	st.global.f32 	[%rd17], %f10;

$L__BB0_10:
	ret;

}

`
