// Code generated by cudago. Edit at your own risk.
package cudago

import (
    "github.com/InternatBlackhole/cudago/cuda"
	"unsafe"
)


//here just to force usage of unsafe package
var __razdalja_3_useless_var__ unsafe.Pointer = nil

const (
	KeyRazdalja_3 = "razdalja_3"
)


type vectordistance3Args struct {
    p uintptr
    a uintptr
    b uintptr
    len int32

}

/*var (
    vectordistance3Args = vectordistance3Args{}

)*/







func VectorDistance3(grid, block cuda.Dim3, p uintptr, a uintptr, b uintptr, len int32) error {
	err := autoloadLib_razdalja_3()
	if err != nil {
		return err
	}
	kern, err := getKernel("razdalja_3", "vectorDistance3")
	if err != nil {
		return err
	}
	
	params := vectordistance3Args{
	    p: p,
	    a: a,
	    b: b,
	    len: len,
	
	}
	
	return kern.Launch(grid, block, unsafe.Pointer(&params.p), unsafe.Pointer(&params.a), unsafe.Pointer(&params.b), unsafe.Pointer(&params.len))
}

func VectorDistance3Ex(grid, block cuda.Dim3, sharedMem uint64, stream *cuda.Stream, p uintptr, a uintptr, b uintptr, len int32) error {
	err := autoloadLib_razdalja_3()
	if err != nil {
		return err
	}
	kern, err := getKernel("razdalja_3", "vectorDistance3")
	if err != nil {
		return err
	}
	
	params := vectordistance3Args{
	    p: p,
	    a: a,
	    b: b,
	    len: len,
	
	}
	
	return kern.LaunchEx(grid, block, sharedMem, stream, unsafe.Pointer(&params.p), unsafe.Pointer(&params.a), unsafe.Pointer(&params.b), unsafe.Pointer(&params.len))
}



var loaded_razdalja_3 = false


var pathToCompile_razdalja_3 = "razdalja-3.cu"
func autoloadLib_razdalja_3() error {
	var code []byte
	if loaded_razdalja_3 {
		return nil
	}
	code, err := compileFile(pathToCompile_razdalja_3)
	if err != nil {
		return err
	}
	err = InitLibrary([]byte(code), "razdalja_3")
	if err != nil {
		return err
	}
	loaded_razdalja_3 = true
	return nil
}

