// Code generated by cudago. Edit at your own risk.
package cudago

import (
	"unsafe"

	"github.com/InternatBlackhole/cudago/cuda"
)

// here just to force usage of unsafe package
var __vecsub_4_useless_var__ unsafe.Pointer = nil

const (
	KeyVecsub_4 = "vecsub_4"
)

type vectorsubtract4Args struct {
	c   uintptr
	a   uintptr
	b   uintptr
	len int32
}

/*var (
    vectorsubtract4Args = vectorsubtract4Args{}

)*/

func VectorSubtract4(grid, block cuda.Dim3, c uintptr, a uintptr, b uintptr, len int32) error {
	err := autoloadLib_vecsub_4()
	if err != nil {
		return err
	}
	kern, err := getKernel("vecsub_4", "vectorSubtract4")
	if err != nil {
		return err
	}

	params := vectorsubtract4Args{
		c:   c,
		a:   a,
		b:   b,
		len: len,
	}

	return kern.Launch(grid, block, unsafe.Pointer(&params.c), unsafe.Pointer(&params.a), unsafe.Pointer(&params.b), unsafe.Pointer(&params.len))
}

func VectorSubtract4Ex(grid, block cuda.Dim3, sharedMem uint64, stream *cuda.Stream, c uintptr, a uintptr, b uintptr, len int32) error {
	err := autoloadLib_vecsub_4()
	if err != nil {
		return err
	}
	kern, err := getKernel("vecsub_4", "vectorSubtract4")
	if err != nil {
		return err
	}

	params := vectorsubtract4Args{
		c:   c,
		a:   a,
		b:   b,
		len: len,
	}

	return kern.LaunchEx(grid, block, sharedMem, stream, unsafe.Pointer(&params.c), unsafe.Pointer(&params.a), unsafe.Pointer(&params.b), unsafe.Pointer(&params.len))
}

var loaded_vecsub_4 = false

var pathToCompile_vecsub_4 = "./vecsub-4.cu"

func autoloadLib_vecsub_4() error {
	var code []byte
	if loaded_vecsub_4 {
		return nil
	}
	code, err := compileFile(pathToCompile_vecsub_4)
	if err != nil {
		return err
	}
	err = InitLibrary([]byte(code), "vecsub_4")
	if err != nil {
		return err
	}
	loaded_vecsub_4 = true
	return nil
}
