// Code generated by cudago. Edit at your own risk.
package cudago

import (
	"unsafe"

	"github.com/InternatBlackhole/cudago/cuda"
)

// here just to force usage of unsafe package
var __vecsub_3_useless_var__ unsafe.Pointer = nil

const (
	KeyVecsub_3 = "vecsub_3"
)

type vectorsubtract3Args struct {
	c   uintptr
	a   uintptr
	b   uintptr
	len int32
}

/*var (
    vectorsubtract3Args = vectorsubtract3Args{}

)*/

func VectorSubtract3(grid, block cuda.Dim3, c uintptr, a uintptr, b uintptr, len int32) error {
	err := autoloadLib_vecsub_3()
	if err != nil {
		return err
	}
	kern, err := getKernel("vecsub_3", "vectorSubtract3")
	if err != nil {
		return err
	}

	params := vectorsubtract3Args{
		c:   c,
		a:   a,
		b:   b,
		len: len,
	}

	return kern.Launch(grid, block, unsafe.Pointer(&params.c), unsafe.Pointer(&params.a), unsafe.Pointer(&params.b), unsafe.Pointer(&params.len))
}

func VectorSubtract3Ex(grid, block cuda.Dim3, sharedMem uint64, stream *cuda.Stream, c uintptr, a uintptr, b uintptr, len int32) error {
	err := autoloadLib_vecsub_3()
	if err != nil {
		return err
	}
	kern, err := getKernel("vecsub_3", "vectorSubtract3")
	if err != nil {
		return err
	}

	params := vectorsubtract3Args{
		c:   c,
		a:   a,
		b:   b,
		len: len,
	}

	return kern.LaunchEx(grid, block, sharedMem, stream, unsafe.Pointer(&params.c), unsafe.Pointer(&params.a), unsafe.Pointer(&params.b), unsafe.Pointer(&params.len))
}

var loaded_vecsub_3 = false

var pathToCompile_vecsub_3 = "./vecsub-3.cu"

func autoloadLib_vecsub_3() error {
	var code []byte
	if loaded_vecsub_3 {
		return nil
	}
	code, err := compileFile(pathToCompile_vecsub_3)
	if err != nil {
		return err
	}
	err = InitLibrary([]byte(code), "vecsub_3")
	if err != nil {
		return err
	}
	loaded_vecsub_3 = true
	return nil
}
