// Code generated by cudago. Edit at your own risk.
package cudago

import (
    "github.com/InternatBlackhole/cudago/cuda"
	"unsafe"
)


//here just to force usage of unsafe package
var __razdalja_8b_useless_var__ unsafe.Pointer = nil

const (
	KeyRazdalja_8b = "razdalja_8b"
)


type vectordistance8bArgs struct {
    sPtr uintptr
    a uintptr
    b uintptr
    len int32

}

/*var (
    vectordistance8bArgs = vectordistance8bArgs{}

)*/







func VectorDistance8b(grid, block cuda.Dim3, sPtr uintptr, a uintptr, b uintptr, len int32) error {
	err := autoloadLib_razdalja_8b()
	if err != nil {
		return err
	}
	kern, err := getKernel("razdalja_8b", "vectorDistance8b")
	if err != nil {
		return err
	}
	
	params := vectordistance8bArgs{
	    sPtr: sPtr,
	    a: a,
	    b: b,
	    len: len,
	
	}
	
	return kern.Launch(grid, block, unsafe.Pointer(&params.sPtr), unsafe.Pointer(&params.a), unsafe.Pointer(&params.b), unsafe.Pointer(&params.len))
}

func VectorDistance8bEx(grid, block cuda.Dim3, sharedMem uint64, stream *cuda.Stream, sPtr uintptr, a uintptr, b uintptr, len int32) error {
	err := autoloadLib_razdalja_8b()
	if err != nil {
		return err
	}
	kern, err := getKernel("razdalja_8b", "vectorDistance8b")
	if err != nil {
		return err
	}
	
	params := vectordistance8bArgs{
	    sPtr: sPtr,
	    a: a,
	    b: b,
	    len: len,
	
	}
	
	return kern.LaunchEx(grid, block, sharedMem, stream, unsafe.Pointer(&params.sPtr), unsafe.Pointer(&params.a), unsafe.Pointer(&params.b), unsafe.Pointer(&params.len))
}



var loaded_razdalja_8b = false


func autoloadLib_razdalja_8b() error {
	if loaded_razdalja_8b {
		return nil
	}
	err := InitLibrary([]byte(Razdalja_8b_ptxCode), "razdalja_8b")
	if err != nil {
		return err
	}
	loaded_razdalja_8b = true
	return nil
}

const Razdalja_8b_ptxCode = `//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-34431801
// Cuda compilation tools, release 12.6, V12.6.20
// Based on NVVM 7.0.1
//

.version 8.5
.target sm_52
.address_size 64

	// .globl	vectorDistance8b
.extern .shared .align 16 .b8 part[];

.visible .entry vectorDistance8b(
	.param .u64 vectorDistance8b_param_0,
	.param .u64 vectorDistance8b_param_1,
	.param .u64 vectorDistance8b_param_2,
	.param .u32 vectorDistance8b_param_3
)
{
	.reg .pred 	%p<3>;
	.reg .f32 	%f<6>;
	.reg .b32 	%r<12>;
	.reg .b64 	%rd<13>;


	ld.param.u64 	%rd4, [vectorDistance8b_param_0];
	ld.param.u64 	%rd5, [vectorDistance8b_param_1];
	ld.param.u64 	%rd6, [vectorDistance8b_param_2];
	ld.param.u32 	%r6, [vectorDistance8b_param_3];
	mov.u32 	%r7, %tid.x;
	mul.wide.u32 	%rd7, %r7, 4;
	mov.u64 	%rd8, part;
	add.s64 	%rd9, %rd8, %rd7;
	mov.u32 	%r8, 0;
	st.shared.u32 	[%rd9], %r8;
	mov.u32 	%r1, %ntid.x;
	mov.u32 	%r9, %ctaid.x;
	mad.lo.s32 	%r11, %r9, %r1, %r7;
	setp.ge.s32 	%p1, %r11, %r6;
	@%p1 bra 	$L__BB0_3;

	mov.u32 	%r10, %nctaid.x;
	mul.lo.s32 	%r3, %r10, %r1;
	cvta.to.global.u64 	%rd1, %rd5;
	cvta.to.global.u64 	%rd2, %rd6;
	cvta.to.global.u64 	%rd3, %rd4;

$L__BB0_2:
	mul.wide.s32 	%rd10, %r11, 4;
	add.s64 	%rd11, %rd1, %rd10;
	add.s64 	%rd12, %rd2, %rd10;
	ld.global.f32 	%f1, [%rd12];
	ld.global.f32 	%f2, [%rd11];
	sub.f32 	%f3, %f2, %f1;
	mul.f32 	%f4, %f3, %f3;
	atom.global.add.f32 	%f5, [%rd3], %f4;
	add.s32 	%r11, %r11, %r3;
	setp.lt.s32 	%p2, %r11, %r6;
	@%p2 bra 	$L__BB0_2;

$L__BB0_3:
	ret;

}

`
