// Code generated by cudago. Edit at your own risk.
package cudago

import (
    "github.com/InternatBlackhole/cudago/cuda"
	"unsafe"
)


//here just to force usage of unsafe package
var __razlika_1_useless_var__ unsafe.Pointer = nil

const (
	KeyRazlika_1 = "razlika_1"
)


type vectorsubtract1Args struct {
    c uintptr
    a uintptr
    b uintptr
    len int32

}

/*var (
    vectorsubtract1Args = vectorsubtract1Args{}

)*/







func VectorSubtract1(grid, block cuda.Dim3, c uintptr, a uintptr, b uintptr, len int32) error {
	err := autoloadLib_razlika_1()
	if err != nil {
		return err
	}
	kern, err := getKernel("razlika_1", "vectorSubtract1")
	if err != nil {
		return err
	}
	
	params := vectorsubtract1Args{
	    c: c,
	    a: a,
	    b: b,
	    len: len,
	
	}
	
	return kern.Launch(grid, block, unsafe.Pointer(&params.c), unsafe.Pointer(&params.a), unsafe.Pointer(&params.b), unsafe.Pointer(&params.len))
}

func VectorSubtract1Ex(grid, block cuda.Dim3, sharedMem uint64, stream *cuda.Stream, c uintptr, a uintptr, b uintptr, len int32) error {
	err := autoloadLib_razlika_1()
	if err != nil {
		return err
	}
	kern, err := getKernel("razlika_1", "vectorSubtract1")
	if err != nil {
		return err
	}
	
	params := vectorsubtract1Args{
	    c: c,
	    a: a,
	    b: b,
	    len: len,
	
	}
	
	return kern.LaunchEx(grid, block, sharedMem, stream, unsafe.Pointer(&params.c), unsafe.Pointer(&params.a), unsafe.Pointer(&params.b), unsafe.Pointer(&params.len))
}



var loaded_razlika_1 = false


func autoloadLib_razlika_1() error {
	if loaded_razlika_1 {
		return nil
	}
	err := InitLibrary([]byte(Razlika_1_ptxCode), "razlika_1")
	if err != nil {
		return err
	}
	loaded_razlika_1 = true
	return nil
}

const Razlika_1_ptxCode = `//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-34431801
// Cuda compilation tools, release 12.6, V12.6.20
// Based on NVVM 7.0.1
//

.version 8.5
.target sm_52
.address_size 64

	// .globl	vectorSubtract1

.visible .entry vectorSubtract1(
	.param .u64 vectorSubtract1_param_0,
	.param .u64 vectorSubtract1_param_1,
	.param .u64 vectorSubtract1_param_2,
	.param .u32 vectorSubtract1_param_3
)
{
	.reg .f32 	%f<4>;
	.reg .b32 	%r<2>;
	.reg .b64 	%rd<11>;


	ld.param.u64 	%rd1, [vectorSubtract1_param_0];
	ld.param.u64 	%rd2, [vectorSubtract1_param_1];
	ld.param.u64 	%rd3, [vectorSubtract1_param_2];
	cvta.to.global.u64 	%rd4, %rd1;
	cvta.to.global.u64 	%rd5, %rd3;
	cvta.to.global.u64 	%rd6, %rd2;
	mov.u32 	%r1, %tid.x;
	mul.wide.s32 	%rd7, %r1, 4;
	add.s64 	%rd8, %rd6, %rd7;
	ld.global.nc.f32 	%f1, [%rd8];
	add.s64 	%rd9, %rd5, %rd7;
	ld.global.nc.f32 	%f2, [%rd9];
	sub.f32 	%f3, %f1, %f2;
	add.s64 	%rd10, %rd4, %rd7;
	st.global.f32 	[%rd10], %f3;
	ret;

}

`
